export class ListPages {
  static readonly ChooseCity = 'ChooseCity'
  static readonly ChooseMaster = 'ChooseMaster'
  static readonly EnterPhoneNumberSingIn = 'EnterPhoneNumberSingIn'
  static readonly PasswordSingIn = 'PasswordSingIn'
  static readonly EnterPhoneNumberSingInRegistration = 'EnterPhoneNumberSingInRegistration'
  static readonly PasswordRegistration = 'PasswordRegistration'
  static readonly MainPage = 'MainPage'
  static readonly MainTab = 'MainTab'
  static readonly RegistrationContacts = 'RegistrationContacts'
  static readonly Masters = 'Masters'
  static readonly AppointmentType = 'AppointmentType'
  static readonly SelectService = 'SelectService'
  static readonly MyNotesStack = 'MyNotesStack'
  static readonly MyNotes = 'MyNotes'
  static readonly NoteDetails = 'NoteDetails'
  static readonly TimeSelect = 'TimeSelect'
  static readonly Сontacts = 'Сontacts'
  static readonly ChooseSalon = 'ChooseSalon'
  static readonly FinishNote = 'FinishNote'
  static readonly Enroll = 'Enroll'
 
}
