export class ImageRepository {
  static readonly loaderBackground = require('../../../assets/images/loader/background.png')
  static readonly chooseCityCheck = require('assets/images/chooseCity/icon.png')
  static readonly logo = require('assets/images/main/logo.png')
  static readonly sign = require('assets/images/main/signService.png')
  static readonly recordingMaster = require('assets/images/main/recordingMaster.png')
  static readonly solariumAppointment = require('assets/images/main/solariumAppointment.png')
  static readonly changeLocation = require('assets/images/main/changeLocation.png')
  static readonly exit = require('assets/images/main/exit.png')
  static readonly arrowRight = require('assets/images/main/arrowRight.png')
  static readonly profile = require('assets/images/main/profile.png')
  static readonly contacts = require('assets/images/main/contacts.png')
  static readonly menu = require('assets/images/main/menu.png')
  static readonly disabledRecordingMaster = require('assets/images/main/disableRecordingMaster.png')
  static readonly disabledSign = require('assets/images/main/disableSign.png')
  static readonly contactsCheckMark = require('assets/images/main/contactsCheckMark.png')
}